### ISSUE TITLE
Fetching for /dashboard/ via the frontend is resulting in 404

### ISSUE THREAD

**Issue by matthewroysl** [ech0r/SNSText#2]
Trying to access /dashboard/ resources (w/ auth token in headers) is resulting in a 404, even though the resource does exist.

404 Error after fetching:
![image](https://user-images.githubusercontent.com/79606430/109575588-f647ea00-7aa6-11eb-9d39-aac5c4724622.png)

Resources **does** exist in the FE, as shown here:
https://github.com/ech0r/SNSText/blob/master/templates/dashboard/init.js
![image](https://user-images.githubusercontent.com/79606430/109575128-0f9c6680-7aa6-11eb-826b-afe8f92d83fd.png)

The code executing the GET fetch request for this resource:
https://github.com/ech0r/SNSText/blob/fbbd1e893d415086c86bb67a31f27cdb574ec29c/templates/login/res/js/login.js#L4
https://github.com/ech0r/SNSText/blob/fbbd1e893d415086c86bb67a31f27cdb574ec29c/templates/login/res/js/login.js#L164-L181

**Comment by matthewroysl** [comment]
@ech0r , issue seems to persist on user SNS, still. FYI!

**Comment by ech0r** [comment]
You’ll need to show me what you’re doing, it works for me

**Comment by matthewroysl** [comment]
@ech0r fixed this in the latest update.
